on:
  push:
    branches: [ master ]
jobs:
  Aranga:
    runs-on: ubuntu-latest
    steps:     
      - uses: actions/checkout@v2

      - name: boman
        run: |
          sudo pip install --extra-index-url https://test.pypi.org/simple/ boman-cli-uat==0.8
          sudo boman-cli-uat -a run -u https://devapi.boman.ai/v2/
    
