on:
  push:
    branches: [ master ]
jobs:
  Aranga:
    runs-on: ubuntu-latest
    steps:     
      - uses: actions/checkout@v2

      - name: Build
        run: |
          dotnet restore
          dotnet build
    
