on:
  push:
    branches: [ master ]
jobs:
  Boman:
    runs-on: ubuntu-latest
    steps:     
      - uses: actions/checkout@v2

      - name: boman
        run: |
          sudo pip install boman-cli
          sudo boman-cli -a run 
    
